export const SET_SELECTED_HAPPENING = 'SET_SELECTED_HAPPENING';
export const UPDATE_HAPPENING = 'UPDATE_HAPPENING';

export const PENDING_TASK_BEGIN = 'PENDING_TASK_BEGIN';
export const PENDING_TASK_END = 'PENDING_TASK_END';

export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';

export const USER_UPDATE_INTERESTS_REQUESTED = 'USER_UPDATE_INTERESTS_REQUESTED';
export const USER_UPDATE_INTERESTS_SUCCEEDED = 'USER_UPDATE_INTERESTS_SUCCEEDED';

export const ADD_HAPPENING_REQUESTED = 'ADD_HAPPENING_REQUESTED';
export const ADD_HAPPENING_SUCCEEDED = 'ADD_HAPPENING_SUCCEEDED';

export const JOIN_HAPPENING_REQUESTED = 'JOIN_HAPPENING_REQUESTED';
export const JOIN_HAPPENING_SUCCEEDED = 'JOIN_HAPPENING_SUCCEEDED';

export const LEAVE_HAPPENING_REQUESTED = 'LEAVE_HAPPENING_REQUESTED';
export const LEAVE_HAPPENING_SUCCEEDED = 'LEAVE_HAPPENING_SUCCEEDED';

export const HAPPENINGS_FETCH_REQUESTED = 'HAPPENINGS_FETCH_REQUESTED';
export const HAPPENINGS_FETCH_SUCCEEDED = 'HAPPENINGS_FETCH_SUCCEEDED';

export const USER_HAPPENINGS_FETCH_REQUESTED = 'USER_HAPPENINGS_FETCH_REQUESTED';
export const USER_HAPPENINGS_FETCH_SUCCEEDED = 'USER_HAPPENINGS_FETCH_SUCCEEDED';

export const HAPPENING_ADD_COMMENT_REQUESTED = 'HAPPENING_ADD_COMMENT_REQUESTED';
export const HAPPENING_ADD_COMMENT_SUCCEEDED = 'HAPPENING_ADD_COMMENT_SUCCEEDED';
