export const ADD_HAPPENING = 'ADD_HAPPENING';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_SELECTED_HAPPENING = 'SET_SELECTED_HAPPENING';
export const UPDATE_HAPPENING = 'UPDATE_HAPPENING';

export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';

export const HAPPENINGS_FETCH_REQUESTED = 'HAPPENINGS_FETCH_REQUESTED';
export const HAPPENINGS_FETCH_SUCCEEDED = 'HAPPENINGS_FETCH_SUCCEEDED';