export const SET_SELECTED_HAPPENING = 'SET_SELECTED_HAPPENING';
export const UPDATE_HAPPENING = 'UPDATE_HAPPENING';

export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';

export const ADD_HAPPENING_REQUESTED = 'ADD_HAPPENING_REQUESTED';
export const ADD_HAPPENING_SUCCEEDED = 'ADD_HAPPENING_SUCCEEDED';
export const HAPPENINGS_FETCH_REQUESTED = 'HAPPENINGS_FETCH_REQUESTED';
export const HAPPENINGS_FETCH_SUCCEEDED = 'HAPPENINGS_FETCH_SUCCEEDED';
export const HAPPENING_ADD_COMMENT_REQUESTED = 'HAPPENING_ADD_COMMENT_REQUESTED';
export const HAPPENING_ADD_COMMENT_SUCCEEDED = 'HAPPENING_ADD_COMMENT_SUCCEEDED';
